In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix
dataset=pd.read_csv("C:/AIandMLAssigment/train.csv")
dataset.columns


Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:

dataset = dataset.drop(['PassengerId','Name','Ticket','Cabin'], axis=1)


In [10]:

le = LabelEncoder()
dataset['Sex'] = le.fit_transform(dataset['Sex'])
dataset['Embarked'] = le.fit_transform(dataset['Embarked'])


In [11]:
def Test(col):
    x = dataset.drop([col], axis=1)
    y = dataset[col]
    train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state = 42)
    model = BernoulliNB()
    model.fit(train_x, train_y)
    ypred = model.predict(test_x)
    print(f"Accuracy score is {accuracy_score(test_y, ypred)}")
    print("-------------------------------------")
    print(f"Confusion Matrix: \n{confusion_matrix(test_y, ypred)}")

In [12]:
Test('Pclass')

Accuracy score is 0.5786516853932584
-------------------------------------
Confusion Matrix: 
[[15 10 19]
 [ 0  8 34]
 [ 6  6 80]]


In [13]:
Test('SibSp')

Accuracy score is 0.6910112359550562
-------------------------------------
Confusion Matrix: 
[[108  17   0   0   0   0]
 [ 28  15   0   0   0   0]
 [  3   2   0   0   0   0]
 [  1   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  0   1   0   0   0   0]]


In [14]:
Test('Sex')

Accuracy score is 0.797752808988764
-------------------------------------
Confusion Matrix: 
[[53 20]
 [16 89]]


In [15]:
Test('Parch')

Accuracy score is 0.6966292134831461
-------------------------------------
Confusion Matrix: 
[[118  15   0   0   0]
 [ 24   6   0   0   0]
 [ 10   2   0   0   0]
 [  1   0   0   0   0]
 [  1   1   0   0   0]]


In [16]:
Test('Embarked')

Accuracy score is 0.7303370786516854
-------------------------------------
Confusion Matrix: 
[[  0   0  36]
 [  0   0  12]
 [  0   0 130]]
