In [1]:
"""
1. Create a 3x3x3 array with random values
"""


import numpy as np
x = np.random.random((3,3,3))
print("3x3x3 array with random values",x)


3x3x3 array with random values [[[0.54343907 0.40753856 0.23434684]
  [0.89866581 0.67205601 0.51991153]
  [0.98016275 0.44029631 0.40755457]]

 [[0.67516336 0.89327184 0.06293444]
  [0.06315776 0.15928277 0.8473947 ]
  [0.27238788 0.06568159 0.63472011]]

 [[0.22738327 0.88219224 0.17598953]
  [0.51646573 0.13553043 0.9190954 ]
  [0.04008537 0.1984731  0.40107236]]]


In [2]:
"""
Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
"""

import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print("5x5 matrix with values 1,2,3,4 just below the diagonal",x)


5x5 matrix with values 1,2,3,4 just below the diagonal [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
#3.Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
#4.Normalize a 5x5 random matrix

import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.13360524 0.91271932 0.96706097 0.68630184 0.30544413]
 [0.36905378 0.39146032 0.44200588 0.8545869  0.04092585]
 [0.46148379 0.91638175 0.32756363 0.778591   0.91721914]
 [0.17464961 0.73324552 0.39212323 0.23016661 0.28768975]
 [0.16606567 0.78011057 0.36211408 0.19842451 0.78950771]]
After normalization:
[[0.10007113 0.94132427 1.         0.69684863 0.2856152 ]
 [0.35429812 0.37849171 0.43306859 0.87855543 0.        ]
 [0.45409997 0.9452788  0.30949887 0.79649841 0.94618298]
 [0.14438903 0.74753635 0.37920749 0.20433385 0.26644481]
 [0.13512047 0.79813917 0.34680493 0.17006013 0.80828578]]


In [6]:
#5.How to find common values between two arrays
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [7]:
#6.How to get the dates of yesterday, today and tomorrow
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


In [13]:
#7.Consider two random array A and B, check if they are equal
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,4,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 1 1 1 0]
Second array:
[3 0 1 3 1 3]
Test above two arrays are equal or not!
False


In [14]:
#8.Create random vector of size 10 and replace the maximum value by 0
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] =0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.19034134 0.67894069 0.35577658 0.85264537 0.35958418 0.28228528
 0.98338977 0.83612685 0.43460825 0.92573167]
Maximum value replaced by 0:
[0.19034134 0.67894069 0.35577658 0.85264537 0.35958418 0.28228528
 0.         0.83612685 0.43460825 0.92573167]


In [20]:
#9. How to print all the values of an array?

import numpy as np
import sys
nums = np.arange(5)
np.set_printoptions(threshold=sys.maxsize)
print(nums)

[0 1 2 3 4]


In [21]:
# 10.Subtract the mean of each row of a matrix
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.54501218 0.13790405 0.1574215  0.35592399 0.82112944 0.56617488
  0.96162187 0.39255501 0.07957404 0.2857763 ]
 [0.84403965 0.80455801 0.16832988 0.45192455 0.26895496 0.59319795
  0.32895533 0.93017896 0.40005325 0.84511137]
 [0.56159322 0.5989371  0.58154791 0.29923709 0.49922929 0.89358122
  0.02677911 0.89169199 0.66720517 0.3573757 ]
 [0.32401038 0.33336489 0.56228861 0.10338516 0.42162276 0.97697063
  0.81171329 0.90829388 0.91593155 0.09985516]
 [0.07852182 0.37046205 0.53152964 0.87408414 0.34638889 0.2318894
  0.76050461 0.367989   0.53791899 0.66917935]]

Subtract the mean of each row of the said matrix:

[[ 0.11470285 -0.29240528 -0.27288782 -0.07438533  0.39082011  0.13586555
   0.53131255 -0.03775431 -0.35073528 -0.14453303]
 [ 0.28050926  0.24102762 -0.39520051 -0.11160584 -0.29457543  0.02966756
  -0.23457506  0.36664857 -0.16347714  0.28158098]
 [ 0.02387544  0.06121932  0.04383013 -0.23848069 -0.03848849  0.35586345
  -0.51093867  0.35397421  0.12

In [41]:
#11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

import numpy as np
A = np.array([1,2,3])
B = np.array([10,20,30])
I = np.array([0,1,1])
np.add.at(A, I, B)
print(A)

None
[11 52  3]


In [35]:
# 12.How to get the diagonal of a dot product?
import numpy as np
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 10, (3,3))

print(a.dot(b))

np.diagonal(a.dot(b))
print(np.einsum('ij,ji->i', a,b))


[[119 125 112]
 [ 57  74  66]
 [113 135 122]]
[119  74 122]


In [36]:
#13.How to find the most frequent value in an array
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[7 1 2 3 2 7 1 0 1 7 8 3 4 5 7 8 9 7 1 0 6 2 4 9 3 1 8 9 5 8 1 4 8 0 9 0 4
 6 6 9]
Most frequent value in the above array:
1


In [37]:
#14.How to get the n largest values of an array
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


In [38]:
#15.How to create a record array from a regular array

import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
